//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncoraApp.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class encoraEntities : DbContext
    {
        public encoraEntities()
            : base("name=encoraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<note> notes { get; set; }
        public virtual DbSet<user> users { get; set; }

        public System.Data.Entity.DbSet<EncoraApp.Models.NotesModel> NotesModels { get; set; }
    }
}
